services:
  api:
    build: .
    container_name: project3
    ports:
    - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DEBUG: ${DEBUG}
      ROOT_PASSWORD: ${ROOT_PASSWORD}
    depends_on:
    - db

  db:
    image: postgres:17.5
    container_name: postgres_db
    restart: always 
    ports:
    - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
    - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: