name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      
      - name: Run linting
        run: |
          ruff check .
          black --check .
      
      - name: Create .env file
        run: |
          echo "ROOT_PASSWORD=${{ secrets.ROOT_PASSWORD }}" >> .env
          echo "DATABASE_URL=sqlite+aiosqlite:///:memory:" >> .env
        
      - name: Run tests with pytest
        run: pytest -vv